[package]
name = "weblog-diesel"
version = "0.1.0"
authors = ["foxboxpdx@gmail.com"]

[dependencies]
diesel = { version = "0.99.0", features = ["sqlite"] }
diesel_infer_schema = { version = "0.99.0", features = ["sqlite"] }
dotenv = "0.9.0"
regex = "0.2"
lazy_static = "0.2"
